import React from "react";
import {
  WiCloud,
  WiNightCloudy,
  WiDaySunnyOvercast,
  WiDayCloudy,
  WiNightAltCloudy,
  WiCloudy,
  WiDayFog,
  WiDayHaze,
  WiDayWindy,
  WiFog,
  WiRainMix,
  WiRainWind,
  WiRain,
  WiSandstorm,
  WiSleet,
  WiShowers,
  WiSprinkle,
  WiLightning,
  WiDaySnowThunderstorm,
  WiDayThunderstorm,
} from "weather-icons-react";

export const weatherIcons: { [key: string]: React.FC<{ size: number }> } = {
  "Fair (Day)": WiCloud,
  "Fair (Night)": WiNightCloudy,
  "Fair & Warm": WiDaySunnyOvercast,
  "Partly Cloudy (Day)": WiDayCloudy,
  "Partly Cloudy (Night)": WiNightAltCloudy,
  Cloudy: WiCloudy,
  Hazy: WiDayFog,
  "Slightly Hazy": WiDayHaze,
  Windy: WiDayWindy,
  Mist: WiFog,
  "Light Rain": WiRainMix,
  "Moderate Rain": WiRainWind,
  "Heavy Rain": WiRain,
  "Passing Showers": WiSandstorm,
  "Light Showers": WiSleet,
  Showers: WiShowers,
  "Heavy Showers": WiSprinkle,
  "Thundery Showers": WiLightning,
  "Heavy Thundery Showers": WiDaySnowThunderstorm,
  "Heavy Thundery Showers with Gusty Winds": WiDayThunderstorm,
};
